services:
  db:
    image: postgres:latest
    container_name: imsick_db
    environment:
      POSTGRES_USER: imsick
      POSTGRES_PASSWORD: imsick123
      POSTGRES_DB: postgres
    ports:
      - "8000:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: